# Generated by Django 2.2 on 2020-10-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_a', models.IntegerField(max_length=10, verbose_name='Число А')),
                ('string_b', models.IntegerField(max_length=10, verbose_name='Число Б')),
            ],
        ),
    ]
