# Generated by Django 2.2 on 2020-10-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='string_a',
            field=models.IntegerField(verbose_name='Число А'),
        ),
        migrations.AlterField(
            model_name='counts',
            name='string_b',
            field=models.IntegerField(verbose_name='Число Б'),
        ),
    ]
