# Generated by Django 2.2 on 2020-10-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201015_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='counts',
            name='answer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
